### ISSUE TITLE
Update the Text on 3 of the pages

### ISSUE THREAD

**Issue by profRic** [DukeMobileDevCenter/Jigsaw#125]
Hannah asked that some text on the pages be updated.  There are 3 total changes.  I attached her markups here as 3 images.  I am assigning this to Courtney to work on.

----------------
**1.**
![IMG_4788](https://user-images.githubusercontent.com/26363642/107036831-38bc2680-6788-11eb-9458-faee82fee68c.PNG)

----------------
**2.**
![IMG_4790](https://user-images.githubusercontent.com/26363642/107036852-41acf800-6788-11eb-9de8-7fab2d9b20eb.PNG)

-----------------
**3.**
![IMG_4791](https://user-images.githubusercontent.com/26363642/107036462-b2074980-6787-11eb-831e-63b8a79a6903.PNG)

**Comment by yo1995** [comment]
Text 1 is defined in the questionnaires stored in Google Firebase

Text 2 and 3 are hardcoded in the app, in this file L25-L53

https://github.com/DukeMobileDevCenter/Jigsaw/blob/233352dd3ae3f0afb39d25946b5e5257f71d27b7/Jigsaw-app/Jigsaw/Controllers/Home/GameViewController.swift#L25-L53

**Comment by profRic** [comment]
Ting - thanks!  At some point I will have to introduce you to Courtney.  I want to wait until she has some questions gathered before taking too much of your time.
