### ISSUE TITLE
[URGENT] Need to figure out how to eliminate this warning from Apple

### ISSUE THREAD

**Issue by profRic** [DukeMobileDevCenter/Jigsaw#126]
TMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1

**Comment by yo1995** [comment]
This warning might be introduced by using 3rd party Google's Firebase related pods. Our app does not use APN.

This info can be safely ignored. To avoid receiving such email, we have 2 choices

- Either add push notification capability to the app
    currently we don't use it in our app and there are no plan to add push notification in the near future. so I didn't add it to the app to avoid confusion. But we can definitely add it.
- Or disable the push service on the website, in the developer's panel.
    I don't know if it is doable, but we may try disable it from this site: https://developer.apple.com/account/resources/identifiers/bundleId and find the bundle identifier to edit it.
![image](https://user-images.githubusercontent.com/9660181/107077161-53e76000-67a1-11eb-950a-ff8c1bbbd3e4.png)

**Comment by profRic** [comment]
Thanks.  I would like to get rid of it if we don't use it.  Seems like it should be somewhere in a .plist in the workspace, no?

**Comment by yo1995** [comment]
> Thanks. I would like to get rid of it if we don't use it. Seems like it should be somewhere in a .plist in the workspace, no?

I don't think I've specified anything related to APN in the app (plist, project file, etc.)

Please try with the link https://developer.apple.com/account/resources/identifiers/bundleId , and go to the app id to see if we can uncheck the box shown above.

If not, we might have to **add** an entry to the app's plist saying the app uses APN, to silence this warning.

**Comment by profRic** [comment]
Push is not selected.  Only Apple Sign in is checked and can be deselected.  For some reason the Game Center and InApp Purchases are checked and can't be changed.

**Comment by yo1995** [comment]
OK... Then we'll need to try to remove the 3rd party code using notification functionalities... or ignore it. 😕
