### ISSUE TITLE
Change to the ChatRoom view

### ISSUE THREAD

**Issue by profRic** [DukeMobileDevCenter/Jigsaw#128]
Per Hannah's comment below in the attached image, we don't need the puzzle piece chat bubble to appear - maybe we just have it say "Hi, your partner is here!" or something like that.  Let's review with Hannah before we change code.

---------------------
![IMG_4797](https://user-images.githubusercontent.com/26363642/107077278-9c5f4780-67ba-11eb-94c6-1defba05973b.PNG)

**Comment by cej8** [comment]
Hannah liked changing the puzzle piece to a wave, and I changed the goodbye message to a double wave

**Comment by profRic** [comment]
Great!  So you have the code in a branch somewhere?  I guess the next step is to create a pull request and make sure and link it to this Issue.
