### ISSUE TITLE
[Implementation] Integration of Qualtrics Survey into Jigsaw

### ISSUE THREAD

**Issue by profRic** [DukeMobileDevCenter/Jigsaw#139]
For a first test, I think the easiest thing to do is add a button called "Take Survey" to the Profile page / tab.  This should go to a WebView of the Qualtrics URL.  Try this for now and we can get feedback from Hannah and Sam and Walter.

**Comment by anshudwibhashi** [comment]
Task completed. Here are screenshots of what it looks like on my device:

<img width="200" alt="Screenshot 2021-06-13 at 5 50 03 PM" src="https://user-images.githubusercontent.com/14247244/121822931-edeb7780-cc6f-11eb-8aac-776ea64bb7ba.png">
<img width="200" alt="Screenshot 2021-06-13 at 5 50 55 PM" src="https://user-images.githubusercontent.com/14247244/121822932-edeb7780-cc6f-11eb-9d88-c447efce53d9.png">
