### ISSUE TITLE
[Logistic] Get school App Store server up and running

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#8]
If we want our customers to download the app next time we meet, we'll need to have a way to deliver our app.

We can either utilize Duke App Store, or somehow meet in person to upload the app to their phone? 🤔 

@profRic

**Comment by profRic** [comment]
Plan A would be the app store - if it is running which i doubt.  Plan B will be for me to load on 2 iPhones I have here and deliver them to Walter and Hannah, assuming Hannah is in town - I will ask her.

**Comment by yo1995** [comment]
Revisit and will discuss more in the next few days. A few choices

- School AppStore
- Personal TestFlight
- Zoom video demo

**Comment by yo1995** [comment]
Seems not possible right now. Close and wait for further updates.
