### ISSUE TITLE
[Logistic] Get access to original Firebase server

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#9]
According to original documentation:

> The Firebase project can be accessed at:
https://console.firebase.google.com/u/0/project/jigsaw-25200/overview

We need to access that server, or at least its back-end code base, to extract useful pieces.

@profRic Could you help with this issue? I'm unsure what is the status of the server, but I get "Access denied" when I access the link above. This issue need to be fixed sooner than later to avoid blocking back-end development.

**Comment by profRic** [comment]
what Google ID are you using / want to use?  I can add you to the auth table if you are not already

**Comment by yo1995** [comment]
> what Google ID are you using / want to use? I can add you to the auth table if you are not already

My Google ID is the same as my gmail, 
![image](https://user-images.githubusercontent.com/9660181/87962968-df4f0d00-ca6c-11ea-91dc-2291898476a8.png)

**Comment by profRic** [comment]
Try now

**Comment by profRic** [comment]
oops - didn't mean to close yet

**Comment by yo1995** [comment]
Yep I can see the database now. Will dig more during the week.
